version: "3.7"
services:
  entity-and-event-generator-db:
    image: postgres
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
#    volumes:
#            - ../../../data/postgres:/var/lib/postgresql/data