version: "3.7"
services:
  mobile-operator-personal-account-db:
    image: postgres
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
#        volumes:
#            - ../../../data/postgres:/var/lib/postgresql/data